name: Docker Image CI | Push to DockerHub

on:
  push:
    branches: [ "master" , "production" ]
  pull_request:
    branches: [ "master" ]

env:
  BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
  GROUP_CHAT_ID: '${{ secrets.GROUP_CHAT_ID }}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          --build-arg GROUP_CHAT_ID=${{ secrets.GROUP_CHAT_ID }} \
          --tag tg-cvbot-scrape:latest

    - name: Build and Push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: lagometro/telegram-bot-cv-collector
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
